### PR TITLE
visual tweaks to the UI

### PR DESCRIPTION
**Pull request by rlagerweij**
These changes were made because it was difficult for me to see whether saving new settings actually worked. 

This pull request gives the buttons a slight 3d effect so that you can visually see the "click". The messages related to saving the settings were made more verbose and more noticeable.

There are some minor layout changes to the tables included as well.

In the end it is a visual preference rather than a real technical improvement, but I think it is worth including this in the next release

### CODE REVIEW

**Comment by rvdbreemen** [comment]
great improvement

**Comment by rvdbreemen** [comment]
So this is how the visual improvement to the tabel looks on iPhone X. 

image

This is what is was:
image

Not sure what you changed now. Could you help me get this right?

**Comment by rvdbreemen** [comment]
Ok, I reverted the width on the otmonitor style, to 270px. That works better. Why did you change it?

**Comment by rlagerweij** [comment]
adding the 10px left margin led to the table being to narrow and the over flowing on one of the items. I hadn't considered phone screens when I increased the width of the column.

**Pull request merged**
